<?php

namespace maxcom\catalog\exportimport;

class Module extends \yii\base\Module {

    public $controllerNamespace = 'maxcom\catalog\exportimport\admin\controllers';

    public function init()
    {
        parent::init(); // TODO: Change the autogenerated stub
    }
}