<?php

namespace maxcom\catalog\exportimport;

class Module extends \yii\base\Module {

    public $controllerNamespace = 'maxcom\catalog\exportimport\admin\controllers';

    public function getMenuItems() {
        return [
            'url' => '#',
            'label' => 'CSV Импорт/Экспорт',
            'icon' => 'refresh',
            'items' => [
                ['url' => ['/import-export/default/import'], 'label' => 'Импорт'],
                ['url' => ['/import-export/default/export'], 'label' => 'Экспорт']
            ]
        ];
    }

    public function init()
    {
        parent::init(); // TODO: Change the autogenerated stub
    }
}